image cheerleader_club1         = "images/event/cheerleader_club/cheerleader_club1.jpg"
image cheerleader_club2         = "images/event/cheerleader_club/cheerleader_club2.jpg"
image cheerleader_club3-1       = "images/event/cheerleader_club/cheerleader_club3-1.jpg"
image cheerleader_club3-2       = "images/event/cheerleader_club/cheerleader_club3-2.jpg"
image cheerleader_club4-1       = "images/event/cheerleader_club/cheerleader_club4-1.jpg"
image cheerleader_club4-2       = "images/event/cheerleader_club/cheerleader_club4-2.jpg"
image cheerleader_club5         = "images/event/cheerleader_club/cheerleader_club5.jpg"
image cheerleader_club6         = "images/event/cheerleader_club/cheerleader_club6.jpg"